//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7eam_sondeo_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.SONDEO = new HashSet<SONDEO>();
        }
    
        public string ID_PRODUCTO { get; set; }
        public string ID_CATEGORIA { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
        public string ID_MARCA { get; set; }
        public string PRODUCTO1 { get; set; }
        public string PRESENTACION { get; set; }
        public decimal PRECIO_CONSULTA { get; set; }
        public string TIPO { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SONDEO> SONDEO { get; set; }
    }
}
